[project]
name = "ok-end-field"
version = "0.1.0"
description = "Endfield game automation built on ok-script"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ok-script==1.0.180",
    "onnxocr-ppocrv5==0.0.14",
    "openvino==2026.0.0",
    "opencv-python==4.12.0.88",
    "websocket-client==1.9.0",
    "websockets==15.0.1",
    "json5==0.15.0",
    "pynput==1.8.2",
    "imagehash==4.3.2",
    "pyautogui==0.9.54",
    "scikit-image==0.26.0",
    "playwright==1.57.0",
    "pytesseract==0.3.13",
]

[dependency-groups]
dev = [
    "polib",
]

[tool.uv]
package = false
